events {
  worker_connections  4096;
}
http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"'
                           '$upstream_addr $upstream_response_time $request_time ';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log;

    upstream userservice {
        server user-service:8001;
    }
    upstream publishservice {
        server publish-service:8002;
    }
    upstream commentservice {
        server comment-service:8003;
    }
    upstream favoriteservice {
        server favorite-service:8004;
    }
    upstream relationservice {
        server relation-service:8005;
    }
    upstream messageservice {
        server message-service:8006;
    }
    server {
        listen       80;
        server_name  nginx;

        location /douyin/user/ {
            proxy_pass   http://userservice;
        }
        location /douyin/user/register/ {
            proxy_pass   http://userservice;
        }
        location /douyin/user/login/ {
            proxy_pass   http://userservice;
        }
        location /douyin/publish/action/ {
            client_max_body_size 100m;
            proxy_pass   http://publishservice;
        }
        location /douyin/publish/list/ {
            proxy_pass   http://publishservice;
        }
        location /douyin/feed {
            proxy_pass   http://publishservice;
        }
        location /douyin/favorite/list/ {
            proxy_pass   http://favoriteservice;
        }
        location /douyin/favorite/action/ {
            proxy_pass   http://favoriteservice;
        }
        location /douyin/relation/follow/list/ {
            proxy_pass   http://relationservice;
        }
        location /douyin/relation/action/ {
            proxy_pass   http://relationservice;
        }
        location /douyin/relation/follower/list/ {
            proxy_pass   http://relationservice;
        }
        location /douyin/relation/friend/list/ {
            proxy_pass   http://relationservice;
        }
        location /douyin/message/chat/ {
            proxy_pass   http://messageservice;
        }
        location /douyin/message/action/ {
            proxy_pass   http://messageservice;
        }
        location /douyin/comment/list/ {
            proxy_pass   http://commentservice;
        }
        location /douyin/comment/action/ {
            proxy_pass   http://commentservice;
        }
    }
}